<<<<<<< HEAD
# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wikicloth}
  s.version = "0.5.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nricciar", "epitron"]
  s.date = %q{2010-12-10}
  s.email = %q{nricciar@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Rakefile",
    "init.rb",
    "lib/wikicloth.rb",
    "lib/wikicloth/core_ext.rb",
    "lib/wikicloth/lexer.rb",
    "lib/wikicloth/parser.rb",
    "lib/wikicloth/section.rb",
    "lib/wikicloth/token.rb",
    "lib/wikicloth/wiki_buffer.rb",
    "lib/wikicloth/wiki_buffer/html_element.rb",
    "lib/wikicloth/wiki_buffer/link.rb",
    "lib/wikicloth/wiki_buffer/table.rb",
    "lib/wikicloth/wiki_buffer/var.rb",
    "lib/wikicloth/wiki_link_handler.rb",
    "sample_documents/air_force_one.wiki",
    "sample_documents/cheatsheet.wiki",
    "sample_documents/default.css",
    "sample_documents/elements.wiki",
    "sample_documents/george_washington.wiki",
    "sample_documents/images.wiki",
    "sample_documents/lists.wiki",
    "sample_documents/pipe_trick.wiki",
    "sample_documents/random.wiki",
    "sample_documents/tv.wiki",
    "sample_documents/wiki.png",
    "sample_documents/wiki_tables.wiki",
    "tasks/wikicloth_tasks.rake",
    "test/test_helper.rb",
    "test/wiki_cloth_test.rb"
  ]
  s.homepage = %q{http://github.com/epitron/wikicloth}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An implementation of the mediawiki (Wikipedia) markup in Ruby}
  s.test_files = [
    "test/test_helper.rb",
    "test/wiki_cloth_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<expression_parser>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<expression_parser>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<expression_parser>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

=======
require 'rake'
require File.join(File.dirname(__FILE__),'init')

spec = Gem::Specification.new do |s|
  s.name = "wikicloth"
  s.version = WikiCloth::VERSION
  s.author = "David Ricciardi"
  s.email = "nricciar@gmail.com"
  s.homepage = "http://github.com/nricciar/wikicloth"
  s.platform = Gem::Platform::RUBY
  s.summary = "An implementation of the mediawiki markup in ruby"
  s.files = FileList["{lib,tasks}/**/*"].to_a +
    FileList["sample_documents/*.wiki"].to_a +
    ["init.rb","uninstall.rb","Rakefile","install.rb"]
  s.require_path = "lib"
  s.description = File.read("README")
  s.test_files = FileList["{test}/*.rb"].to_a + ["run_tests.rb"]
  s.has_rdoc = false
  s.extra_rdoc_files = ["README","MIT-LICENSE"]
  s.description = %q{mediawiki parser}
  s.add_dependency 'builder'
  s.add_dependency 'expression_parser'
  s.add_development_dependency 'test-unit'
  s.add_development_dependency 'activesupport'
end
>>>>>>> 14841f942a1389ea9c2bab9eb6804169d0908425
